(()=>{
'use strict';
const MILITARES=[['19.0251.73','CB','CPA-QPA CE','CANAL','03/01'],['99.0874.04','2TEN','CA-CA','THIAGO SANTOS','06/01'],['13.0796.97','CC','CA-CA','BARJONAS','14/01'],['13.0080.72','3SG','CAP-QAP EF','MAGDINIER','21/01'],['14.1694.79','3SG','CPA-QPA CO','LOBO','01/02'],['19.0074.51','CB','CPA-QPA CO','DYLVER','06/02'],['23.0349.47','MN','CPA-QPA','PEDRO','18/02'],['23.0533.48','MN','CPA-QPA','COSTA','24/02'],['08.0188.12','2SG','CPA-QPA ET','JOHNNY','14/03'],['02.2174.06','CB','CPA-QPA CE','PASSOS','16/03'],['14.0118.75','3SG','CPA-QPA MA','CHARLES','21/03'],['86.9315.39','3SG','CPA-QPA MT','THEMOTEO','25/03'],['15.0115.34','1TEN','CA-CA','MARTINS','16/04'],['03.0076.69','1SG','CPA-QPA MO','MOZART','25/04'],['07.2472.65','2TEN','CA-CA','ABDALLA','03/05'],['10.0183.28','2SG','CPA-QPA AR','ROBSON CHAGAS','06/05'],['12.0223.73','3SG','CPA-QPA EL','DÉNYTON','08/05'],['20.0352.41','CB','CPA-QPA OR','PASCОAL','18/05'],['19.0075.15','CB','CPA-QPA MP','BRYAN','05/06'],['11.0128.54','1TEN','CA-CA','FALCÃO','11/06'],['99.2091.01','SO','CPA-QPA CP','REIS','24/06'],['11.0305.85','2SG','CPA-QPA ET','NETO','25/06'],['12.0472.87','1TEN','CA-CA','MARCUS BEZERRA','01/07'],['18.0069.57','CB','CPA-QPA CN','ANDERSON','08/07'],['11.0261.71','2SG','CPA-QPA SI','MATEUS','14/07'],['11.0305.18','2SG','CPA-QPA MR','ALVES','17/07'],['21.0942.41','CB','CPA-QPA MR','OHANA','17/07'],['10.0273.35','CT','CA-CA','ABREU','02/09'],['07.3616.11','2SG','CPA-QPA MO','FREITAS','07/09'],['05.0285.82','1SG','CAP-QAP PL','DANIEL','10/09'],['06.0341.87','1SG','CPA-QPA CN','CLÉBERSON','14/09'],['96.1163.82','SO','CPA-QPA MR','JOSEBIAS JUNIOR','17/09'],['19.0084.65','CB','CPA-QPA AM','EDGARD','19/09'],['10.0092.81','2SG','CPA-QPA MR','EVERTON','26/09'],['12.0208.77','3SG','CPA-QPA EL','FREITAS','01/10'],['06.0364.06','1SG','CPA-QPA HN','SARAIVA','04/10'],['20.0687.43','CB','CAP-QAP PL','ERIC COSTA','12/10'],['21.0876.44','CB','CPA-QPA CN','AROUCHE','27/10'],['15.0325.82','3SG','CPA-QPA MO','PANTOJA','01/11'],['23.0445.43','MN','CPA-QPA','LEANDRO','15/11'],['08.0191.85','2SG','CPA-QPA AM','MARQUINY','01/12']].map(([nip,post,cqea,nome,data])=>({nip,post,cqea,nome,data}));
const OMS=[['CDA','','',''],['CPAOR','Capitania dos Portos da Amazônia Oriental','19/05',1846],['CPAP','Capitania dos Portos do Amapá','05/07',1899],['AgOiapoque *','Agência da Capitania dos Portos do Oiapoque','26/02',2019],['CPMA','Capitania dos Portos do Maranhão','28/07',1846],['AgImperatriz *','Agência Fluvial de Imperatriz','23/02',1989],['CPPI','Capitania dos Portos do Piauí','10/02',1855],['CFS','Capitania Fluvial de Santarém','20/02',1918],['ComGptPatNavN','Comando do Grupamento de Patrulha Naval do Norte','23/04',1974],['ERMBe','Estação Radiogoniométrica da Marinha em Belém','08/01',1969],['2°BtlOpRib','2º Batalhão de Operações Ribeirinhas','13/10',1932],['EsqdHU-41','1º Esquadrão de Helicópteros de Emprego Geral do Norte','20/05',2019],['CHN-4','Centro de Hidrografia e Navegação do Norte','26/05',1956],['GrEOpRibN ','Grupo de Embarcações de Operações Ribeirinhas do Norte','04/08',2021],['BNVC','Base Naval de Val de Cães','25/07',1949],['CeIMBe','Centro de Intendência da Marinha em Belém','12/05',1995],['CIABA','Centro de Instrução Almirante Braz de Aguiar','13/10',1892],['HNBe','Hospital Naval de Belém','31/12',1958],['NhiBTenCastelo ','Navio Hidrográfico Balizador "Tenente Castelo"','15/12',1983],['NhoGSampaio ','Navio Hidroceanográfico "Garnier Sampaio"','31/01',1995],['AvHoFluRioTocantins ','Aviso Hidroceanográfico Fluvial “Rio Tocantins”','27/07',2012],['AvHoFluRioXingu ','Aviso Hidroceanográfico Fluvial "Rio Xingú"','29/01',2013],['NapOcIguatemi ','Navio de Apoio Oceânico “Iguatemi”','09/07',2018],['NpaBocaina ','Navio-Patrulha "Bocaina"','10/07',1998],['NpaBracui ','Navio-Patrulha "Bracuí"','08/04',1984],['NpaGuanabara ','Navio-Patrulha "Guanabara"','09/07',1999],['NpaGuaruja ','Navio-Patrulha "Guarujá"','30/11',1999],['NPaPampeiro','Navio-Patrulha “Pampeiro”','16/06',1971],['NAPara ','Navio-Auxiliar “Pará”','19/01',2005],['NasHSGLima','Navio de Assistência Hospitalar Sargento Lima','',null],['GRNAsHAnnaNery','Navio de Assistência Hospitalar Anna Nery','',null]].map(([sigla,nome,data,ano])=>({sigla,nome,data,ano}));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function info(ddmm){if(!ddmm)return null;const [d,m]=ddmm.split('/').map(Number);if(!d||!m)return null;const now=new Date();now.setHours(0,0,0,0);let y=now.getFullYear();let date=new Date(y,m-1,d);if(date<now)date=new Date(y+1,m-1,d);return {date,days:Math.round((date-now)/86400000)};}
const fmt=d=>d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'});
const items=a=>a.filter(x=>info(x.data)).map(x=>({...x,info:info(x.data)})).sort((a,b)=>a.info.days-b.info.days);
const stat=d=>d===0?'today':d<=30?'near':'';
const CSS=`.aniv-wrap{padding:0 0 40px}.aniv-hero{background:linear-gradient(135deg,#0b3158,#174c7c);color:#fff;border-radius:18px;padding:24px 28px;margin-bottom:20px;box-shadow:0 8px 22px rgba(11,45,82,.12)}.aniv-hero h2{margin:0 0 6px;font-size:30px}.aniv-hero p{margin:0;opacity:.88}.aniv-alerts,.aniv-next{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:20px}.aniv-next{grid-template-columns:repeat(2,minmax(0,1fr))}.aniv-alert,.aniv-card{border-radius:16px;padding:18px;background:#fff;border:1px solid #cbd8e6;box-shadow:0 5px 14px rgba(11,45,82,.07)}.aniv-alert .label,.aniv-kicker{font-size:12px;font-weight:900;text-transform:uppercase;color:#68758a}.aniv-alert .value{font-size:25px;font-weight:900;color:#0b3158;margin-top:5px}.aniv-alert.urgent,.aniv-card.near{border-color:#e2b21a;background:#fff9df}.aniv-alert.urgent .value{color:#9a6b00}.aniv-card h3{margin:6px 0;color:#0b3158}.aniv-card .date{font-weight:700;color:#596b80;line-height:1.5}.aniv-count{display:inline-block;margin-top:10px;border-radius:999px;padding:6px 10px;background:#edf4fb;color:#0b3158;font-weight:900;font-size:13px}.aniv-count.near{background:#f2c300;color:#102a47}.aniv-count.today{background:#198754;color:#fff}.aniv-tabs{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}.aniv-tab{border:1px solid #5c7897;background:#173f68;color:#fff;border-radius:12px;padding:13px 18px;font-weight:800;cursor:pointer}.aniv-tab.active{background:#f2c300;color:#102a47;border-color:#f2c300}.aniv-panel{display:none}.aniv-panel.active{display:block}.aniv-tablebox{background:#fff;border:1px solid #cbd8e6;border-radius:16px;overflow:hidden;box-shadow:0 5px 14px rgba(11,45,82,.06)}.aniv-tablehead{padding:16px 18px;background:#0b3158;color:#fff;display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.aniv-tablehead strong{font-size:18px}.aniv-search{border:1px solid #d1dbe7;border-radius:9px;padding:9px 12px;min-width:240px;font-size:14px}.aniv-scroll{overflow:auto}.aniv-table{width:100%;border-collapse:collapse;min-width:700px}.aniv-table th{background:#f2c300;color:#102a47;text-align:left;padding:11px 12px;font-size:12px;text-transform:uppercase}.aniv-table td{padding:11px 12px;border-bottom:1px solid #e1e8ef;color:#17324f}.aniv-table tr.near td{background:#fff8d9}.aniv-table tr.today td{background:#dff5e7;font-weight:800}.aniv-badge{display:inline-block;border-radius:999px;padding:4px 8px;font-size:12px;font-weight:900;background:#eef3f8;color:#52667b}.aniv-badge.near{background:#f2c300;color:#102a47}.aniv-badge.today{background:#198754;color:#fff}.aniv-note{margin-top:12px;color:#6b7888;font-size:13px}@media(max-width:850px){.aniv-alerts,.aniv-next{grid-template-columns:1fr}.aniv-search{min-width:0;width:100%}}`;
function make(){
 let old=document.getElementById('anivDataPanel')||document.getElementById('aniversariantes');
 if(!old){const page=document.querySelector('.page');if(!page)return;old=document.createElement('section');old.id='aniversariantes';old.className='view';page.appendChild(old)}
 if(document.getElementById('anivDataPanel'))return;
 const st=document.createElement('style');st.textContent=CSS;document.head.appendChild(st);
 old.id='anivDataPanel';
 old.innerHTML=`<div class="aniv-wrap"><div class="aniv-hero"><h2>🎂 ANIVERSARIANTES</h2><p>Militares/ Organizações Militares</p></div><div class="aniv-alerts" id="anivAlerts"></div><div class="aniv-tabs"><button class="aniv-tab active" type="button" data-tab="mil">🎖️ Aniversários dos Militares</button><button class="aniv-tab" type="button" data-tab="om">⚓ Aniversários das OMs</button></div><div class="aniv-panel active" id="anivMil"><div class="aniv-next" id="anivNextMil"></div><div class="aniv-tablebox"><div class="aniv-tablehead"><strong>Banco de aniversários dos militares</strong><input class="aniv-search" id="anivSearchMil" placeholder="Buscar militar..."></div><div class="aniv-scroll"><table class="aniv-table"><thead><tr><th>NIP</th><th>Post/Grad</th><th>CQEA</th><th>Nome de Guerra</th><th>Aniversário</th><th>Próximo</th></tr></thead><tbody id="anivRowsMil"></tbody></table></div></div></div><div class="aniv-panel" id="anivOm"><div class="aniv-next" id="anivNextOm"></div><div class="aniv-tablebox"><div class="aniv-tablehead"><strong>Banco de aniversários das OMs</strong><input class="aniv-search" id="anivSearchOm" placeholder="Buscar OM..."></div><div class="aniv-scroll"><table class="aniv-table"><thead><tr><th>Sigla</th><th>Organização Militar</th><th>Aniversário</th><th>Ano de criação</th><th>Próximo</th></tr></thead><tbody id="anivRowsOm"></tbody></table></div></div><div class="aniv-note">As OMs NasHSGLima e GRNAsHAnnaNery permanecem sem data, exatamente como na planilha de origem.</div></div></div>`;
 const nm=items(MILITARES),no=items(OMS),all=nm.concat(no).sort((a,b)=>a.info.days-b.info.days),first=all[0],soon=all.filter(x=>x.info.days<=30).length;
 const card=(x,mil)=>`<div class="aniv-card ${stat(x.info.days)}"><div class="aniv-kicker">${mil?'🎖️ Militar':'⚓ Organização Militar'}</div><h3>${esc(mil?x.post+' '+x.nome:x.sigla)}</h3><div class="date">${esc(mil?x.cqea:x.nome)}<br>${fmt(x.info.date)} · ${x.data}</div><span class="aniv-count ${stat(x.info.days)}">${x.info.days===0?'É hoje':x.info.days===1?'Amanhã':'Faltam '+x.info.days+' dias'}</span></div>`;
 document.getElementById('anivNextMil').innerHTML=nm.slice(0,2).map(x=>card(x,true)).join('');
 document.getElementById('anivNextOm').innerHTML=no.slice(0,2).map(x=>card(x,false)).join('');
 document.getElementById('anivRowsMil').innerHTML=nm.map(x=>`<tr class="${stat(x.info.days)}"><td>${esc(x.nip)}</td><td>${esc(x.post)}</td><td>${esc(x.cqea)}</td><td><strong>${esc(x.nome)}</strong></td><td>${x.data}</td><td><span class="aniv-badge ${stat(x.info.days)}">${x.info.days===0?'Hoje':'em '+x.info.days+' dias'}</span></td></tr>`).join('');
 document.getElementById('anivRowsOm').innerHTML=no.map(x=>`<tr class="${stat(x.info.days)}"><td><strong>${esc(x.sigla)}</strong></td><td>${esc(x.nome)}</td><td>${x.data}</td><td>${x.ano}</td><td><span class="aniv-badge ${stat(x.info.days)}">${x.info.days===0?'Hoje':'em '+x.info.days+' dias'}</span></td></tr>`).join('');
 document.getElementById('anivAlerts').innerHTML=`<div class="aniv-alert ${first&&first.info.days<=30?'urgent':''}"><div class="label">Próximo aniversário</div><div class="value">${first?esc(first.nome||first.sigla):'—'}</div><div>${first?fmt(first.info.date)+' · faltam '+first.info.days+' dias':'Nenhuma data cadastrada'}</div></div><div class="aniv-alert ${soon?'urgent':''}"><div class="label">Nos próximos 30 dias</div><div class="value">${soon}</div><div>aniversário(s) cadastrados</div></div><div class="aniv-alert"><div class="label">Banco de dados</div><div class="value">${MILITARES.length} + ${OMS.filter(x=>x.data).length}</div><div>militares + OMs com data</div></div>`;
 document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('anivMil').classList.toggle('active',b.dataset.tab==='mil');document.getElementById('anivOm').classList.toggle('active',b.dataset.tab==='om')}));
 const bind=(id,body)=>{const el=document.getElementById(id);if(!el)return;el.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#'+body+' tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')})};
 bind('anivSearchMil','anivRowsMil');bind('anivSearchOm','anivRowsOm');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',make);else make();
})();