(()=>{'use strict';
const $=s=>document.querySelector(s), money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const G=[
['AÇUCAR REFINADO SC 1 KG','KG',4.17],['ALCATRA','KG',36.95],['ARROZ BRANCO TIPO 1 SC 1 KG FA 10 KG','KG',3.56],['AZEITE OLIVA','LI',44.60],['BACON DEFUMADO','KG',29],['BATATA PALHA EMB. COM 500G','UN',22],['BISCOITO CREAM CRACKER','KG',2],['BISCOITO DOCE','KG',2],['CHOCOLATE PO','KG',11.40],['COCADA BRANCA','UN',40],['CONTRA-FILE','KG',39.39],['COXA FRANGO','KG',8.04],['CREME DE LEITE 200G','UN',8.50],['EMPANADO DE FRANGO','KG',19.30],['EXTRATO TOMATE','KG',5.52],['FEIJAO PRETO TIPO 1 SA 1 KG FA 10 KG','KG',3.48],['FERMENTO QUÍMICO EM PÓ, EMB. 100G','UN',26.22],['FILÉ DE DOURADA','KG',37],['GELEIA','KG',8.97],['LEITE EM PÓ INTEGRAL 1KG','PA',37.80],['LEITE PO INSTANTANEO','KG',30.39],['LIMÃO (HTM)','KG',3.16],['LOMBO DE PORCO','KG',18.08],['MACARRÃO ESPAGUETE','KG',3.98],['MANTEIGA COM SAL EMB. 10KG','UN',350],['MORTADELA BOLONHA','KG',25.90],['OVO TIPO EXTRA','DZ',8],['PIMENTÃO VERDE (HTM)','KG',5.27],['POLPA DE CUPUAÇU','UN',12.80],['POLPA DE TAPEREBÁ','KG',7.90],['PRESUNTO COZIDO','KG',22],['PÃO DE FORMA C/500G','UN',8.40],['PÃO FRANCÊS','KG',15.90],['REFRIGERANTE COLA 2L','UN',3.90],['REFRIGERANTE COLA ZERO','UN',6.70],['SAL MESA','KG',1.31],['SUCO CAJU','LI',3.50],['SUCO MARACUJA','LI',6.49],['SUCO UVA','LI',6.41],['ÓLEO VEGETAL','GA',6.85]
];
const get=k=>JSON.parse(localStorage.getItem('bocaina_'+k)||'[]'),put=(k,v)=>localStorage.setItem('bocaina_'+k,JSON.stringify(v));
function css(){if($('#menuBuilderCss'))return;const s=document.createElement('style');s.id='menuBuilderCss';s.textContent=`.builder{background:#eef3f8;padding:12px}.builder-grid{display:grid;grid-template-columns:1.1fr 1.5fr;gap:12px}.builder-card{background:#fff;border:1px solid #cbd9e7;border-radius:9px;padding:12px}.builder-card h3{margin:0 0 10px;color:#102f50;font-size:14px}.builder-form{display:grid;grid-template-columns:1fr .45fr auto;gap:8px;background:#f2c300;padding:10px;border-radius:7px}.builder-form label{font-size:9px;font-weight:900;color:#17324f}.builder-form input,.builder-form select{display:block;width:100%;height:35px;margin-top:4px;border:1px solid #9fb2c6;border-radius:6px;padding:5px;background:#fff}.builder-form button,.builder-btn{height:35px;margin-top:16px;border:0;border-radius:6px;background:#0b2d52;color:#fff;font-weight:800;padding:0 12px;cursor:pointer}.builder-table{width:100%;border-collapse:collapse}.builder-table th{background:#082e53;color:#fff;font-size:10px;padding:8px;text-align:left}.builder-table td{font-size:11px;padding:8px;border-bottom:1px solid #d4e0eb}.builder-total{display:flex;justify-content:space-between;background:#082e53;color:#fff;padding:12px;border-radius:7px;margin-top:10px;font-weight:900}.builder-name{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:10px}.builder-name input{height:36px;border:1px solid #9fb2c6;border-radius:6px;padding:6px}.builder-search{width:100%;height:32px;border:1px solid #b7c7d6;border-radius:5px;padding:5px;margin-bottom:8px}.builder-actions{display:flex;gap:7px;flex-wrap:wrap}.builder-actions button{margin-top:0}.builder-empty{text-align:center;padding:25px;color:#667085}@media(max-width:800px){.builder-grid{grid-template-columns:1fr}.builder-form{grid-template-columns:1fr .6fr}.builder-form button{margin-top:4px}.builder-name{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function build(){const stock=$('#stock');if(!stock||stock.dataset.cardapioReady)return;stock.dataset.cardapioReady='1';css();const nav=stock.querySelector('.stock-subtabs');if(!nav)return;const b=document.createElement('button');b.type='button';b.className='stock-subtab';b.dataset.tab='cardapio';b.textContent='🍽️ Cardápios';nav.appendChild(b);const content=$('#stockSubContent');if(!content)return;const p=document.createElement('section');p.className='stock-panel';p.dataset.panel='cardapio';p.innerHTML=`<div class="builder"><div class="builder-grid"><div class="builder-card"><h3>📚 Banco de Gêneros</h3><input id="genreSearch" class="builder-search" placeholder="Pesquisar gênero..."><div style="max-height:480px;overflow:auto"><table class="builder-table"><thead><tr><th>Gênero</th><th>Unid.</th><th>Preço</th><th></th></tr></thead><tbody id="genreRows"></tbody></table></div></div><div class="builder-card"><h3>🍽️ Composição do Cardápio</h3><div class="builder-name"><input id="menuName" placeholder="Nome do cardápio (ex.: Almoço A)"><button class="builder-btn" id="saveMenu">Salvar</button></div><div class="builder-form"><label>GÊNERO<select id="menuGenre"></select></label><label>QUANTIDADE<input id="menuQty" type="number" min="0" step="0.001" value="1"></label><button id="addIngredient">Adicionar</button></div><div id="ingredientList" style="margin-top:10px"></div><div class="builder-total"><span>CUSTO TOTAL</span><strong id="menuTotal">R$ 0,00</strong></div><div class="builder-actions" style="margin-top:10px"><button class="builder-btn" id="clearMenu">Limpar</button></div></div></div><div class="builder-card" style="margin-top:12px"><h3>💾 Cardápios Salvos</h3><div id="savedMenus"></div></div></div>`;content.appendChild(p);
let current=[];
const renderGenres=()=>{const q=($('#genreSearch').value||'').toLowerCase();$('#genreRows').innerHTML=G.map((g,i)=>({g,i})).filter(x=>!q||x.g[0].toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.g[0])}</td><td>${x.g[1]}</td><td>${money(x.g[2])}</td><td><button class="stock-del" data-add="${x.i}">+</button></td></tr>`).join('')};
const fill=()=>$('#menuGenre').innerHTML=G.map((g,i)=>`<option value="${i}">${esc(g[0])} — ${g[1]} — ${money(g[2])}</option>`).join('');
const renderCurrent=()=>{const total=current.reduce((s,x)=>s+x.qty*x.price,0);$('#menuTotal').textContent=money(total);$('#ingredientList').innerHTML=current.length?`<table class="builder-table"><thead><tr><th>Gênero</th><th>Qtd.</th><th>Preço</th><th>Custo</th><th></th></tr></thead><tbody>${current.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${x.qty} ${x.unit}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td><td><button class="stock-del" data-remove="${i}">Excluir</button></td></tr>`).join('')}</tbody></table>`:'<div class="builder-empty">Adicione os gêneros necessários para confeccionar este cardápio.</div>'};
const renderSaved=()=>{const d=get('menus');$('#savedMenus').innerHTML=d.length?d.map((m,i)=>`<div style="border:1px solid #d4e0eb;border-radius:7px;padding:9px;margin-bottom:7px"><b>${esc(m.name)}</b> — ${m.items.length} itens — <strong>${money(m.total)}</strong><button class="stock-del" style="float:right" data-delmenu="${i}">Excluir</button></div>`).join(''):'<div class="builder-empty">Nenhum cardápio salvo.</div>'};
$('#genreSearch').oninput=renderGenres;renderGenres();fill();renderCurrent();renderSaved();
p.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const g=G[Number(add.dataset.add)];current.push({name:g[0],unit:g[1],price:g[2],qty:1});renderCurrent()}const rem=e.target.closest('[data-remove]');if(rem){current.splice(Number(rem.dataset.remove),1);renderCurrent()}const dm=e.target.closest('[data-delmenu]');if(dm){const d=get('menus');d.splice(Number(dm.dataset.delmenu),1);put('menus',d);renderSaved()}});
$('#addIngredient').onclick=()=>{const g=G[Number($('#menuGenre').value)],q=Number($('#menuQty').value||0);if(q<=0)return;current.push({name:g[0],unit:g[1],price:g[2],qty:q});renderCurrent()};$('#clearMenu').onclick=()=>{current=[];renderCurrent()};$('#saveMenu').onclick=()=>{const name=$('#menuName').value.trim();if(!name||!current.length){alert('Informe o nome e adicione pelo menos um gênero.');return}const total=current.reduce((s,x)=>s+x.qty*x.price,0);const d=get('menus');d.push({name,items:current,total,created:new Date().toISOString()});put('menus',d);current=[];$('#menuName').value='';renderCurrent();renderSaved()};
nav.addEventListener('click',e=>{const btn=e.target.closest('[data-tab="cardapio"]');if(!btn)return;nav.querySelectorAll('.stock-subtab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');content.querySelectorAll('.stock-panel').forEach(x=>x.classList.remove('active'));p.classList.add('active')});
}
function watch(){if(build())return;const m=new MutationObserver(()=>{if(build())m.disconnect()});m.observe(document.body,{childList:true,subtree:true});setTimeout(()=>m.disconnect(),15000)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();