(()=>{'use strict';
const KEY='bocaina_inventory_management_v1';
const HISTORY='bocaina_inventory_history_v1';
const get=(k,def)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(def))}catch{return def}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const qty=n=>Math.max(0,Number(n)||0);
function user(){try{const s=window.supabaseClient?.auth?.getUser?.(); if(s&&typeof s.then==='function')return 'Usuário autenticado';}catch{} return localStorage.getItem('bocaina_usuario')||'Usuário local'}
function data(){return get(KEY,{})} function hist(){return get(HISTORY,[])}
function currentQty(item){const d=data(),v=d[item.id];return v&&v.quantity!=null?v.quantity:(parseInt(item.quantity)||0)}
function minQty(item){const d=data(),v=d[item.id];return v&&v.min!=null?v.min:0}
function ensure(){items.forEach(i=>{const d=data();if(!d[i.id])d[i.id]={quantity:parseInt(i.quantity)||0,min:0};});put(KEY,data())}
function css(){if(document.getElementById('invMgmtCss'))return;const s=document.createElement('style');s.id='invMgmtCss';s.textContent=`.inv-mgmt{background:#fff;border:1px solid #cbd9e7;border-radius:8px;padding:10px;margin:0 0 10px;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.inv-mgmt button{border:0;border-radius:6px;padding:9px 12px;font-weight:800;cursor:pointer}.inv-mgmt .gold{background:#f2c300;color:#102a47}.inv-mgmt .dark{background:#0b2d52;color:#fff}.inv-mgmt .light{background:#edf2f7;color:#17324f}.inv-alert{background:#fff1c7!important}.inv-alert td:first-child{border-left:4px solid #e0a800}.inv-stock-low{color:#b42318;font-weight:900}.inv-stock-ok{color:#18864b;font-weight:800}.inv-modal{position:fixed;inset:0;background:rgba(5,25,45,.65);z-index:9999;display:none;align-items:center;justify-content:center;padding:20px}.inv-modal.open{display:flex}.inv-box{background:#fff;border-radius:12px;max-width:720px;width:100%;max-height:90vh;overflow:auto;padding:18px;box-shadow:0 15px 50px rgba(0,0,0,.3)}.inv-box h3{margin:0 0 12px;color:#102f50}.inv-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.inv-grid label{font-size:11px;font-weight:800;color:#17324f}.inv-grid input,.inv-grid select{display:block;width:100%;box-sizing:border-box;height:38px;margin-top:4px;border:1px solid #b7c7d6;border-radius:6px;padding:6px 8px}.inv-full{grid-column:1/-1}.inv-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.inv-history{width:100%;border-collapse:collapse;font-size:11px}.inv-history th{background:#082e53;color:#fff;text-align:left;padding:7px}.inv-history td{padding:7px;border-bottom:1px solid #dbe4ec}.inv-close{float:right;background:#edf2f7;border:0;border-radius:6px;padding:6px 9px;cursor:pointer}.inv-summary{font-size:11px;color:#667085;margin-left:auto}@media(max-width:700px){.inv-grid{grid-template-columns:1fr}.inv-full{grid-column:auto}.inv-summary{width:100%;margin-left:0}}`;document.head.appendChild(s)}
function toolbar(){if(document.getElementById('invMgmt'))return;const card=document.querySelector('#inventory .table-card');if(!card)return;const b=document.createElement('div');b.className='inv-mgmt';b.id='invMgmt';b.innerHTML='<button class="gold" id="invMove">↕ Registrar entrada/saída</button><button class="dark" id="invHistory">🕘 Histórico</button><button class="light" id="invExport">📊 Excel</button><button class="light" id="invPdf">📄 PDF</button><span class="inv-summary" id="invLow"></span>';card.parentNode.insertBefore(b,card);document.getElementById('invMove').onclick=()=>openMove();document.getElementById('invHistory').onclick=()=>openHistory();document.getElementById('invExport').onclick=exportCsv;document.getElementById('invPdf').onclick=()=>window.print()}
function modal(id,html){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='inv-modal';document.body.appendChild(m)}m.innerHTML='<div class="inv-box">'+html+'</div>';m.classList.add('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};return m}
function openMove(){const m=modal('invMoveModal',`<button class="inv-close" id="invClose">✕</button><h3>Registrar entrada / saída</h3><div class="inv-grid"><label class="inv-full">Material<select id="imItem">${items.map(i=>`<option value="${i.id}">${esc(i.id)} — ${esc(i.material)} (${esc(i.local)}) — estoque: ${currentQty(i)}`).join('')}</select></label><label>Movimentação<select id="imType"><option value="entrada">Entrada</option><option value="saida">Saída</option></select></label><label>Quantidade<input id="imQty" type="number" min="1" step="1" value="1"></label><label>Estoque mínimo<input id="imMin" type="number" min="0" step="1" value="0"></label><label class="inv-full">Observação<input id="imObs" placeholder="Ex.: retirada para cerimônia"></label></div><div class="inv-actions"><button class="light" id="imCancel">Cancelar</button><button class="dark" id="imSave">Salvar movimentação</button></div>`);const sel=m.querySelector('#imItem');const min=m.querySelector('#imMin');const sync=()=>{min.value=minQty(items.find(i=>i.id==sel.value))};sel.onchange=sync;sync();m.querySelector('#invClose').onclick=m.querySelector('#imCancel').onclick=()=>m.classList.remove('open');m.querySelector('#imSave').onclick=()=>{const item=items.find(i=>i.id==sel.value),type=m.querySelector('#imType').value,n=qty(m.querySelector('#imQty').value),minimum=qty(m.querySelector('#imMin').value),d=data();if(!item||n<=0)return alert('Informe uma quantidade válida.');const before=currentQty(item),after=type==='entrada'?before+n:before-n;if(type==='saida'&&n>before)return alert(`Estoque insuficiente. Disponível: ${before}.`);d[item.id]={quantity:after,min:minimum};put(KEY,d);const h=hist();h.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),itemId:item.id,material:item.material,local:item.local,type,quantity:n,before,after,min:minimum,obs:m.querySelector('#imObs').value.trim(),user:user(),at:new Date().toISOString()});put(HISTORY,h);m.classList.remove('open');refresh()}}
function openHistory(){const h=hist();const rows=h.map(x=>`<tr><td>${new Date(x.at).toLocaleString('pt-BR')}</td><td>${esc(x.type==='entrada'?'Entrada':'Saída')}</td><td>${esc(x.material)}</td><td>${x.quantity}</td><td>${x.before} → ${x.after}</td><td>${esc(x.user)}</td><td>${esc(x.obs||'—')}</td></tr>`).join('');modal('invHistoryModal',`<button class="inv-close" onclick="this.closest('.inv-modal').classList.remove('open')">✕</button><h3>Histórico de movimentações</h3><table class="inv-history"><thead><tr><th>Data/hora</th><th>Tipo</th><th>Material</th><th>Qtd.</th><th>Estoque</th><th>Usuário</th><th>Observação</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Nenhuma movimentação registrada.</td></tr>'}</tbody></table>`)}
function refresh(){try{window.renderTable&&window.renderTable()}catch{}setTimeout(()=>{const d=data();document.querySelectorAll('#tbody tr').forEach(tr=>{const id=Number(tr.children[0]?.textContent);const item=items.find(i=>i.id===id);if(!item)return;const q=currentQty(item),min=minQty(item);if(tr.children[3])tr.children[3].innerHTML=min>0&&q<=min?`<span class="inv-stock-low">${q} ⚠️</span>`:`<span class="inv-stock-ok">${q||'—'}</span>`;if(min>0&&q<=min)tr.classList.add('inv-alert')});const low=items.filter(i=>{const m=minQty(i);return m>0&&currentQty(i)<=m}).length;const el=document.getElementById('invLow');if(el)el.textContent=low?`⚠️ ${low} item(ns) abaixo do estoque mínimo`:''},20)}
function exportCsv(){const d=data();const rows=[['ID','Localização','Material','Quantidade atual','Estoque mínimo','Observações'],...items.map(i=>[i.id,i.local,i.material,currentQty(i),minQty(i),i.obs||''])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='inventario-rp.csv';a.click();URL.revokeObjectURL(a.href)}
function init(){if(!window.items||!window.document.querySelector('#inventory'))return;ensure();css();toolbar();refresh();setInterval(()=>{if(document.getElementById('inventory')?.classList.contains('active'))refresh()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);
})();