(()=>{'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), num=v=>Number(v||0), money=v=>num(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const old=k=>{try{return JSON.parse(localStorage.getItem('bocaina_'+k)||'[]')}catch{return[]}};
const read=k=>{try{return JSON.parse(localStorage.getItem('mun_'+k)||'[]')}catch{return[]}};
function css(){if($('#munPraticoCss'))return;const s=document.createElement('style');s.id='munPraticoCss';s.textContent=`.mp-tools{display:flex;gap:7px;align-items:center;flex-wrap:wrap;background:#fff;border:1px solid #cbd9e7;border-radius:9px;padding:9px;margin:0 0 10px}.mp-search{flex:1;min-width:220px;height:36px;border:1px solid #aebfd0;border-radius:7px;padding:0 11px;font-size:12px}.mp-btn{border:0;border-radius:7px;background:#0b2d52;color:#fff;height:36px;padding:0 12px;font-size:10px;font-weight:900;cursor:pointer}.mp-btn.gold{background:#f2c300;color:#102a47}.mp-btn.red{background:#b42318}.mp-badge{background:#eef3f8;border:1px solid #d5e0ea;border-radius:20px;padding:7px 10px;font-size:9px;font-weight:900;color:#17324f}.mp-quick{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin:0 0 11px}.mp-q{background:#fff;border:1px solid #cbd9e7;border-radius:8px;padding:9px;text-align:left;cursor:pointer}.mp-q b{display:block;color:#0b2d52;font-size:10px}.mp-q span{display:block;color:#667085;font-size:9px;margin-top:3px}.mp-year{height:36px;border:1px solid #aebfd0;border-radius:7px;padding:0 8px;font-weight:800}.mp-status{padding:8px 10px;border-radius:7px;background:#f6f8fa;font-size:10px;font-weight:800}.mp-mini-chart{display:flex;gap:7px;align-items:flex-end;height:105px;padding-top:10px}.mp-bar{flex:1;min-width:22px;background:#0b2d52;border-radius:4px 4px 0 0;position:relative}.mp-bar span{position:absolute;bottom:100%;left:50%;transform:translateX(-50%);font-size:8px;font-weight:900;white-space:nowrap}.mp-bar label{position:absolute;top:100%;left:50%;transform:translateX(-50%);font-size:8px;margin-top:3px}.mp-alerts{display:grid;gap:5px}.mp-alert{padding:8px 10px;border-radius:6px;background:#fff4f2;border-left:4px solid #b42318;font-size:10px}.mp-alert.ok{background:#effaf3;border-left-color:#18864b}.mp-hide{display:none!important}@media(max-width:1000px){.mp-quick{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.mp-quick{grid-template-columns:repeat(2,1fr)}.mp-search{min-width:100%}}`;document.head.appendChild(s)}
function data(){const c=old('commitment'),i=old('invoice'),f=JSON.parse(localStorage.getItem('bocainaFoods')||'[]'),m=read('meals'),s=read('suppliers'),l=read('lots');return{c,i,f,m,s,l}};
function go(tab){const b=$(`.stock-subtab[data-tab="${tab}"]`);if(b)b.click();else{const main=$('.nav[data-view="stock"]');main?.click();setTimeout(()=>{$(`.stock-subtab[data-tab="${tab}"]`)?.click()},150)}}
function toolbar(root){if(root.querySelector('#mpToolbar'))return;const t=document.createElement('div');t.id='mpToolbar';t.className='mp-tools';t.innerHTML=`<input class="mp-search" id="mpGlobalSearch" placeholder="🔎 Busca rápida em empenhos, NFs, fornecedores e gêneros..."><select class="mp-year" id="mpYear"><option value="">Todos os anos</option><option>2024</option><option>2025</option><option>2026</option></select><button class="mp-btn gold" id="mpPend">⚠️ Pendências</button><button class="mp-btn" id="mpPrint">🖨️ Imprimir</button><span class="mp-status" id="mpStatus">Gestão pronta</span>`;const title=root.querySelector('.section-title');title?.after(t);t.querySelector('#mpGlobalSearch').oninput=e=>search(e.target.value);t.querySelector('#mpYear').onchange=e=>yearFilter(e.target.value);t.querySelector('#mpPend').onclick=()=>{go('gestao');setTimeout(()=>document.querySelector('#gestaoMunPanel')?.scrollIntoView({behavior:'smooth'}),200)};t.querySelector('#mpPrint').onclick=()=>window.print();}
function quick(root){if(root.querySelector('#mpQuick'))return;const q=document.createElement('div');q.id='mpQuick';q.className='mp-quick';[['commitment','🧾','Novo empenho','Controle financeiro'],['invoice','📄','Nova NF','Recebimento'],['suppliers','🏢','Fornecedor','Cadastro'],['foods','📦','Estoque','Gêneros'],['lots','⏳','Validade','Lotes'],['meals','🍽️','Refeição','Efetivo']].forEach(([tab,ic,a,b])=>{const x=document.createElement('button');x.className='mp-q';x.innerHTML=`<b>${ic} ${a}</b><span>${b}</span>`;x.onclick=()=>go(tab);q.appendChild(x)});const tb=$('#mpToolbar');tb?.after(q)}
function search(q){q=q.trim().toLowerCase();document.querySelectorAll('#stockSubContent table tbody tr').forEach(r=>{r.classList.toggle('mp-hide',!!q&&!r.innerText.toLowerCase().includes(q))});const st=$('#mpStatus');if(st)st.textContent=q?`🔎 Filtrando: ${q}`:'Gestão pronta'}
function yearFilter(y){document.querySelectorAll('#stockSubContent table tbody tr').forEach(r=>{const txt=r.innerText;const hit=!y||txt.includes(y);r.classList.toggle('mp-hide',!hit)});const st=$('#mpStatus');if(st)st.textContent=y?`📅 Ano: ${y}`:'Todos os anos'}
function summary(root){if(root.querySelector('#mpSummary'))return;const d=data(), c=d.c.reduce((s,x)=>s+num(x.value||x.committed),0),p=d.c.reduce((s,x)=>s+num(x.paid),0),pending=d.i.filter(x=>/Pendente|Rejeitada/i.test(x.status||'')).length,low=d.f.filter(x=>num(x.qty)<num(x.min)).length;const box=document.createElement('div');box.id='mpSummary';box.className='ms-box';box.innerHTML=`<h3>⚡ Visão rápida</h3><div class="ms-grid"><div><div class="ms-row"><span>Execução financeira</span><b>${c?((p/c)*100).toFixed(1):0}%</b></div><div class="ms-row"><span>Empenhado</span><b>${money(c)}</b></div><div class="ms-row"><span>A pagar</span><b class="${c-p>0?'warn':'ok'}">${money(c-p)}</b></div></div><div><div class="ms-row"><span>NFs pendentes</span><b class="${pending?'warn':'ok'}">${pending}</b></div><div class="ms-row"><span>Estoque abaixo do mínimo</span><b class="${low?'bad':'ok'}">${low}</b></div><div class="ms-row"><span>Gêneros cadastrados</span><b>${d.f.length}</b></div></div></div>`;const nav=root.querySelector('.stock-subtabs');nav?.after(box)}
function init(){const root=$('#stock');if(!root)return;css();toolbar(root);quick(root);summary(root)}
const mo=new MutationObserver(init);mo.observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();