(()=>{'use strict';
const KEY='bocaina_commitment';
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const isTrue=v=>v===true||v===1||norm(v)==='true'||norm(v)==='sim'||norm(v).startsWith('sim ');
const rows=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
function normalizeSource(r){if(!r||!r.sourceSheet)return r;const sent=isTrue(r.sent);if(r.paid===true){r.paymentStatus='pago';return r}r.paymentStatus=sent?'enviado':'pendente';return r}
function sanitize(){const a=rows();let changed=false;for(const r of a){if(r?.sourceSheet){const before=JSON.stringify([r.sent,r.paid,r.paymentStatus]);normalizeSource(r);if(before!==JSON.stringify([r.sent,r.paid,r.paymentStatus]))changed=true}}if(changed)localStorage.setItem(KEY,JSON.stringify(a));return a}
function payment(r){if(r?.paid===true)return'pago';if(r?.sourceSheet)return isTrue(r.sent)?'enviado':'pendente';const p=norm(r?.paymentStatus),s=norm(r?.statusOrigem||r?.status);if(p==='pago'||p.includes('pago'))return'pago';if(p==='pendente'||p==='pending')return'pendente';if(p.includes('enviado')||p==='enviada')return'enviado';if(s.includes('enviado para pagamento')||s.includes('enviada para pagamento')||isTrue(r?.sent))return'enviado';return'pendente'}
function fix(){const body=document.getElementById('neRows');if(!body)return;const data=sanitize();body.querySelectorAll('tr.ne-row').forEach(row=>{const c=row.children;if(c.length<8)return;const i=Number(row.dataset.i),r=data[i];if(!r)return;const state=payment(r),payBadge=c[6]?.querySelector('.ne-badge'),sitBadge=c[7]?.querySelector('.ne-badge');if(!payBadge||!sitBadge)return;const payText=state==='pago'?'Pago':state==='enviado'?'Enviado para pagamento':'Pendente',payClass=state==='pago'?'ne-badge pago':state==='enviado'?'ne-badge envio':'ne-badge pendente';const sitText=(state==='pago'||state==='enviado')?'Sem crédito':(!r.nf?'Sem NF':Number(r.saldoPlanilha||0)>0?'Com crédito':'Sem crédito'),sitClass=sitText==='Com crédito'?'ne-badge pago':sitText==='Sem NF'?'ne-badge pendente':'ne-badge problema';if(payBadge.textContent.trim()!==payText)payBadge.textContent=payText;if(payBadge.className!==payClass)payBadge.className=payClass;if(sitBadge.textContent.trim()!==sitText)sitBadge.textContent=sitText;if(sitBadge.className!==sitClass)sitBadge.className=sitClass})}
let timer=0,observer=null;function schedule(){clearTimeout(timer);timer=setTimeout(fix,0)}function attach(){const body=document.getElementById('neRows');if(!body)return false;if(observer)observer.disconnect();observer=new MutationObserver(schedule);observer.observe(body,{childList:true,subtree:true});fix();return true}function boot(){if(attach())return;const page=new MutationObserver(()=>{if(attach())page.disconnect()});page.observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();document.addEventListener('bocaina:remote-sync',schedule);window.addEventListener('storage',e=>{if(e.key===KEY)schedule()});})();