(()=>{'use strict';
const U='https://kgfcyfdmvbpjdqycmoft.supabase.co';
const K='sb_publishable_4ahPTqCNF7A-ouDYIZ_cSg_9gUjeYK5';
const T='app_state',P='bocaina_',E=['bocainaFoods'];
let c,tm,pi,last='',syncing=false,applyingRemote=false;
const tracked=k=>String(k).startsWith(P)||E.includes(k);
const snap=()=>{const d={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&tracked(k))d[k]=localStorage.getItem(k)}return d};
function timeout(ms){return new Promise((_,rej)=>setTimeout(()=>rej(new Error('Tempo limite excedido ao conectar ao Supabase.')),ms))}
function css(){if(document.getElementById('sscss'))return;const s=document.createElement('style');s.id='sscss';s.textContent='#cloudSyncStatus{position:fixed;right:16px;bottom:16px;z-index:99990;background:#0b2d52;color:#fff;border-radius:12px;padding:9px 12px;font:700 12px system-ui;box-shadow:0 4px 16px #0003}#cloudSyncModal{position:fixed;inset:0;z-index:100000;background:#071b30cc;display:flex;align-items:center;justify-content:center;padding:18px}#cloudSyncCard{width:min(440px,100%);background:#fff;border-radius:18px;padding:24px;font-family:system-ui;color:#102f50;box-shadow:0 18px 60px #0005}#cloudSyncCard label{display:block;font-size:11px;font-weight:900;margin:10px 0 5px}#cloudSyncCard input{width:100%;box-sizing:border-box;height:42px;border:1px solid #b7c7d6;border-radius:8px;padding:8px 10px;font-size:15px}#cloudSyncLogin{width:100%;height:44px;margin-top:16px;border:0;border-radius:8px;background:#0b2d52;color:#fff;font-weight:900}#cloudSyncLogin:disabled{opacity:.65}#cloudSyncMsg{min-height:18px;margin-top:10px;color:#9b1c1c;font-size:12px;line-height:1.4}';document.head.appendChild(s)}
function st(t){let e=document.getElementById('cloudSyncStatus');if(!e){e=document.createElement('div');e.id='cloudSyncStatus';document.body.appendChild(e)}e.textContent='☁️ '+t}
function modal(){if(document.getElementById('cloudSyncModal'))return;const m=document.createElement('div');m.id='cloudSyncModal';m.innerHTML='<div id="cloudSyncCard"><h2>☁️ Sincronizar NPa Bocaina</h2><p>Entre com o usuário criado no Supabase.</p><label>E-MAIL</label><input id="cloudEmail" type="email" autocomplete="username"><label>SENHA</label><input id="cloudPassword" type="password" autocomplete="current-password"><button id="cloudSyncLogin" type="button">Entrar e sincronizar</button><div id="cloudSyncMsg"></div></div>';document.body.appendChild(m);m.querySelector('#cloudSyncLogin').onclick=login;m.querySelector('#cloudPassword').onkeydown=e=>{if(e.key==='Enter')login()}}
async function login(){const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value,b=document.getElementById('cloudSyncLogin'),msg=document.getElementById('cloudSyncMsg');if(!email||!password){msg.textContent='Informe o e-mail e a senha.';return}b.disabled=true;b.textContent='Conectando...';msg.textContent='';try{if(!c)throw new Error('Cliente Supabase não foi inicializado.');const result=await Promise.race([c.auth.signInWithPassword({email,password}),timeout(12000)]);if(result.error)throw result.error;document.getElementById('cloudSyncModal')?.remove();await sync()}catch(e){console.error('Supabase login/sync:',e);const text=e?.message||'Não foi possível conectar ao Supabase.';msg.textContent=text;b.disabled=false;b.textContent='Entrar e sincronizar';st('Erro de sincronização')}}
async function sync(){if(syncing||applyingRemote)return;syncing=true;try{const u=await Promise.race([c.auth.getUser(),timeout(12000)]);if(u.error)throw u.error;const user=u.data?.user;if(!user){st('Faça login para sincronizar');modal();return}const currentUser=user.email||user.id||'Usuário autenticado';if(localStorage.getItem('bocaina_usuario')!==currentUser){applyingRemote=true;try{localStorage.setItem('bocaina_usuario',currentUser)}finally{applyingRemote=false}}st('Sincronizando...');const q=await Promise.race([c.from(T).select('id,data,updated_at').eq('id',user.id).maybeSingle(),timeout(12000)]);if(q.error)throw q.error;const dataToSave=q.data?{...(q.data.data||{}),...snap()}:snap();const now=new Date().toISOString();const save=await Promise.race([c.from(T).upsert({id:user.id,data:dataToSave,updated_at:now}),timeout(12000)]);if(save.error)throw save.error;last=now;st('Sincronizado');watch()}catch(e){console.error('Supabase sync:',e);st('Erro: '+(e.message||'falha na sincronização'));throw e}finally{syncing=false}}
function watch(){if(window.__bwatch)return;window.__bwatch=true;const p=Storage.prototype,a=p.setItem,r=p.removeItem;p.setItem=function(k,v){const x=a.call(this,k,v);if(this===localStorage&&tracked(k)&&!applyingRemote&&!syncing){clearTimeout(tm);tm=setTimeout(()=>sync().catch(()=>{}),700)}return x};p.removeItem=function(k){const x=r.call(this,k);if(this===localStorage&&tracked(k)&&!applyingRemote&&!syncing){clearTimeout(tm);tm=setTimeout(()=>sync().catch(()=>{}),700)}return x};clearInterval(pi);pi=setInterval(async()=>{if(syncing)return;try{const {data:{session}}=await c.auth.getSession();if(!session)return;const q=await c.from(T).select('data,updated_at').eq('id',session.user.id).maybeSingle();if(q.error||!q.data||!q.data.updated_at||q.data.updated_at===last)return;last=q.data.updated_at;applyingRemote=true;try{Object.entries(q.data.data||{}).forEach(([k,v])=>{if(tracked(k)){const value=String(v);if(localStorage.getItem(k)!==value)localStorage.setItem(k,value)}})}finally{applyingRemote=false}}catch(e){console.error('Supabase watch:',e)}},8000)}
async function boot(){css();if(!window.supabase?.createClient){st('Sincronização indisponível');return}try{c=window.supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});window.bocainaSupabaseClient=c;const {data:{session}}=await Promise.race([c.auth.getSession(),timeout(12000)]);if(session)await sync();else{st('Faça login para sincronizar');modal()}}catch(e){console.error('Supabase boot:',e);st('Erro ao conectar: '+(e.message||'falha'));modal()}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();